DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS drivers;

CREATE TABLE cars (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    color TEXT NOT NULL
);

CREATE TABLE drivers (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    license TEXT NOT NULL,
    car_id BIGINT REFERENCES cars(id)
);
